<?php
/**
 * @category   Syncitgroup
 * @package    Syncitgroup_Sgform
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<form class="" action="<?php echo $block->getBaseUrl().'sgform/group/save'; ?>" id="syncitgroup-sgform-form" method="post" data-mage-init='{"validation": {}}'>
    <fieldset class="fieldset">
        <div class="field note no-label"><?= __("Please Fill All The Details Below")?>.</div>
        <div class="field title">
            <label class="label" for="title"><span><?= __('Title')?></span></label>
            <div class="control">
                <input name="title" id="title" title="Name" value="" class="input-text" type="text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field author">
            <label class="label" for="author"><span><?= __('Author')?></span></label>
            <div class="control">
                <input name="author" id="author" title="Author" value="" class="input-text" type="text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field content">
            <label class="label" for="content"><span><?= __('Content')?></span></label>
            <div class="control">
                <textarea name="content" id="content" title="Content" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span><?=__('Submit')?></span>
            </button>
        </div>
    </div>
</form>